
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *'

name: sync-vip
jobs:
  sync-theme:
    name: sync vip
    runs-on: ubuntu-latest

    steps:
      - name: Setup vip branch
        shell: bash
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

          echo "Cloning create-mantle-app..."
          git clone https://$TOKEN@github.com/alleyinteractive/create-mantle-app.git create-mantle-app

          echo "Cloning wordpress..."
          git clone --depth=1 https://github.com/WordPress/WordPress.git wordpress

          cd create-mantle-app

          echo "Updating vip..."
          git checkout vip
          git merge main --no-edit

          echo "Moving to client-mu-plugins..."
          mv mu-plugins client-mu-plugins

          echo "Merging in vip..."
          set +e
          git remote add vip https://github.com/Automattic/vip-go-skeleton.git
          git fetch vip
          git merge vip/master --no-edit --allow-unrelated-histories || true

          set -e

          echo "Replacing theme..."
          rm -rf themes/twentytwenty
          mv ../wordpress/wp-content/themes/twentytwenty themes/twentytwenty

          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes"
          else
            echo "Committing..."
            git add -A
            git commit -m "Syncing from vip-go-skeleton"
            git push
          fi
